### ISSUE TITLE
[BUG] If the sentence contains . (dot) -- Exception KeyError: '.'

### ISSUE THREAD

**Issue by yoesak** [bookbot-kids/g2p_id#16]
Hi I found that an error when the sentence contains a dot, for example 👇

```
from g2p_id import G2p
g2p = G2p()
print(g2p("Seniornya Brigadir Jendral  A.Yani mengambil alih pimpinan."))

--- will raise an Exception: KeyError: '.'

```

I don't really know phonemes, but what should I do when I have the sentence like that? should I replace the dot in the middle of the sentence to become silent sound? 

But when I tried to give a space between dot and the next word, this library assumes there are two sentences, and only process the first part of the sentence.

I really appreciate your help.

**Comment by w11wo** [comment]
Hi @yoesak.

I am aware of this issue before, and it's a bit of a problem that I've not found a robust solution yet.

This issue will only happen when there's a `.` in the middle of the word, e.g. `A.Yani`, where the `.` serves as contraction to an abbreviation (in this case the name Ahmad). On the other hand, a `.` that serves as a period mark at the end of a sentence has been properly handled by nltk's Tweet Tokenizer [here](https://github.com/bookbot-kids/g2p_id/blob/main/g2p_id/g2p.py#L201), which will split the `.` from the words around it, e.g. `halo. hai.` -> `halo . hai .`.

The best case is to actually expand the abbreviation `A.` to `Ahmad`, the same way that measurements like `km` is expanded to `kilometer`, but this obviously requires a much larger list of common abbreviations in Bahasa Indonesia 😅

In any case, if we'd like to ignore expansions like these, it might just be best to split `A.Yani` to `A. Yani` _OR_ `A Yani`, which will then phonemize it to `[['a'], ['.'], ['j', 'a', 'n', 'i']]` and `[['a'], ['j', 'a', 'n', 'i']]` respectively in the current version. So in your example:

```py
from g2p_id import G2p
g2p = G2p()
print(g2p("Seniornya Brigadir Jendral  A. Yani mengambil alih pimpinan."))
>> [['s', 'ə', 'n', 'i', 'o', 'r', 'ɲ', 'a'], ['b', 'r', 'i', 'ɡ', 'a', 'd', 'i', 'r'], ['dʒ', 'ə', 'n', 'd', 'r', 'a', 'l'], ['a'], ['.'], ['j', 'a', 'n', 'i'], ['m', 'ə', 'ŋ', 'a', 'm', 'b', 'i', 'l'], ['a', 'l', 'i', 'h'], ['p', 'i', 'm', 'p', 'i', 'n', 'a', 'n'], ['.']]
print(g2p("Seniornya Brigadir Jendral  A Yani mengambil alih pimpinan."))
>> [['s', 'ə', 'n', 'i', 'o', 'r', 'ɲ', 'a'], ['b', 'r', 'i', 'ɡ', 'a', 'd', 'i', 'r'], ['dʒ', 'ə', 'n', 'd', 'r', 'a', 'l'], ['a'], ['j', 'a', 'n', 'i'], ['m', 'ə', 'ŋ', 'a', 'm', 'b', 'i', 'l'], ['a', 'l', 'i', 'h'], ['p', 'i', 'm', 'p', 'i', 'n', 'a', 'n'], ['.']]
```

Technically, the first option is only partially correct since the extra `.` in between the phonemes of `ahmad` and `yani` isn't a period mark, and is rather a contraction. Hence why replacing `A.` with `Ahmad` altogether is much more preferable, but hard to implement contextually.

I saw your latest PR that already handles this perfectly. Thanks for your contribution!
